USE ecommerce

SELECT * FROM customers

-- Q.1 Which gender contribute the highest sales revenue?
SELECT
    gender,
    SUM(total_amount) AS total_revenue
FROM customers
GROUP BY gender
ORDER BY total_revenue DESC


-- Q.2 Which age group spends the most on purchases?
SELECT TOP 1
	age_group,
    SUM(total_amount) AS total_spent
FROM customers
GROUP BY age_group
ORDER BY total_spent DESC;


-- Q.3 What is the total sales revenue generated by the company?
SELECT 
	SUM(total_amount) AS total_revenue
FROM customers;


-- Q.4 Which products and categories have the highest sales and customer satisfaction?
SELECT product_name, SUM(quantity) AS total_sales, ROUND(AVG(rating), 2) AS average_rating
FROM customers
GROUP BY product_name
HAVING AVG(rating) >= 3.0
ORDER BY SUM(quantity) DESC, ROUND(AVG(rating), 2) DESC;

SELECT category, SUM(quantity) AS total_sales, ROUND(AVG(rating), 2) AS average_rating
FROM customers
GROUP BY category
HAVING AVG(rating) >= 3.0
ORDER BY SUM(quantity) DESC, ROUND(AVG(rating), 2) DESC;


-- Q.5 Which product categories and products generate the highest revenue?
SELECT TOP 1 product_name, category, SUM(total_amount) AS revenue
FROM customers
GROUP BY product_name, category
ORDER BY revenue DESC;


-- Q.6 Which products are the top-selling based on quantity sold?
SELECT TOP 1
	product_id, 
    product_name, 
    SUM(quantity) AS total_quantity
FROM customers
GROUP BY product_id, product_name
ORDER BY total_quantity DESC;


-- Q.7 Which products receive the highest and lowest customer ratings?
WITH product_ratings AS (
    SELECT
        product_name,
        ROUND(AVG(rating), 2) AS avg_rating
    FROM customers
    GROUP BY product_name
)
SELECT *
FROM product_ratings
WHERE avg_rating = (SELECT MAX(avg_rating) FROM product_ratings)
   OR avg_rating = (SELECT MIN(avg_rating) FROM product_ratings);


-- Q.8 Are there specific countries or customer groups with higher cancellation or return rates?
SELECT country, COUNT(order_status) AS cancel_orders
FROM customers
WHERE order_status IN ('Cancelled', 'Returned')
GROUP BY country
ORDER BY cancel_orders DESC;


-- Q.9 How do payment methods impact purchasing behavior?
SELECT
    payment_method,
    COUNT(*) AS total_orders,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS usage_percentage
FROM customers
GROUP BY payment_method
ORDER BY total_orders DESC;


SELECT
    payment_method,
    COUNT(order_id) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM customers
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- Q.10 What relationship exists between customer reviews, ratings, and repeat purchases?
WITH customer_summary AS (
    SELECT
        customer_id,
        COUNT(order_id) AS total_orders,
        ROUND(AVG(rating), 2) AS avg_rating,
        SUM(total_amount) AS total_revenue
    FROM customers
    GROUP BY customer_id
)
SELECT
    CASE
        WHEN total_orders > 1 THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS customer_type,
    COUNT(*) AS customers,
    ROUND(AVG(avg_rating), 2) AS avg_rating,
    SUM(total_revenue) AS total_revenue
FROM customer_summary
GROUP BY
    CASE
        WHEN total_orders > 1 THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END;


-- Q.11 Which country has the highest number of customers and sales?
SELECT TOP 1
    country,
    COUNT(DISTINCT customer_id) AS total_customers,
    SUM(total_amount) AS total_sales
FROM customers
GROUP BY country
ORDER BY total_customers DESC, total_sales DESC;


-- Q.12 Who are the top 10 repeat customers based on order count?
SELECT TOP 10
    customer_id,
    full_name,
    COUNT(DISTINCT order_id) AS total_orders
FROM customers
GROUP BY customer_id, full_name
ORDER BY total_orders DESC;


-- Q.13 Which product categories contribute the highest revenue?
SELECT TOP 1 category, SUM(total_amount) AS revenue, ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS total_percentage
FROM customers
GROUP BY category
ORDER BY revenue DESC;


-- Q.14 Which products generate the maximum profit/revenue?
SELECT TOP 5 product_name, SUM(total_amount) AS revenue
FROM customers
GROUP BY product_name
ORDER BY revenue DESC;


-- Q.15 How many percentage of Positive, Negative and Neutral reviews have?
SELECT
    ROUND(100.0 * SUM(CASE WHEN rating IN (4, 5) THEN 1 ELSE 0 END) / COUNT(*), 2) AS positive_percentage,
    ROUND(100.0 * SUM(CASE WHEN rating = 3 THEN 1 ELSE 0 END) / COUNT(*), 2) AS neutral_percentage,
    ROUND(100.0 * SUM(CASE WHEN rating IN (1, 2) THEN 1 ELSE 0 END) / COUNT(*), 2) AS negative_percentage
FROM customers;